//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APEXA_LICP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public Nullable<int> AdvisorId { get; set; }
        public Nullable<int> MGAId { get; set; }
        public Nullable<int> CarrierId { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual Carrier Carrier { get; set; }
        public virtual MGA MGA { get; set; }
    }
}
